version: "3.9"
services: 
    app:
        build: .
        ports: 
            - 2000:2000
        depends_on: 
            - db
        environment:
            DATABASE_URL: postgres://docker:${DB_PASSWORD}@db:5432/docker
    db:
        build: .\db
        ports: 
            - 5432:5432
        
